### ISSUE TITLE
[Q] Can absolute filepaths be hidden?

### ISSUE THREAD

**Issue by xplshn** [wepfen/rootkit2600#5]
Hi, currently looking for ways to implement a filldir64 hook that hides absolute paths, instead of all files matching a certain word or prefix. Is it possible to do that with your solution? I'm looking for a way to do this for https://github.com/xplshn/hidefs, which is supposed to be a replacement for GoboHide, thanks!

**Comment by wepfen** [comment]
Hello brother,

Actually the rootkit is made to only hide directory entries so the basename of your absolute path.

Hiding a wanted here : https://github.com/wepfen/rootkit2600/blob/main/src/rootkit/init.c#L54

So yeah it's hiding when matching a certain word or prefix and not the absolute path.
